#!/bin/bash

echo "FULL DB REFRESH..."
psql -U unittest -d unittest -f ./unittest-db/unittest.sql > /tmp/Tfull.log 2>&1
echo "... done"
#redis-cli flushdb
rm -rf ./data

nosetests -v $*
#redis-cli flushdb