
def crm_routes(config):
    rt = config.add_route
    rt('crm.login', '/crm')
    rt('crm.login.post', '/crm/login')
    rt('crm.login.logout', '/crm/logout')

    rt('crm.campaign.list', '/crm/campaign/list')
    rt('crm.campaign.new', '/crm/campaign/new')
    rt('crm.campaign.edit', '/crm/campaign/edit/{campaign_id}')
    rt('crm.campaign.save', '/crm/campaign/save')
    rt('crm.campaign.search', '/crm/campaign/search')

    rt('crm.company.new', '/crm/company/new')
    rt('crm.company.edit', '/crm/company/edit/{company_id}')
    rt('crm.company.save', '/crm/company/save')
    rt('crm.company.search', '/crm/company/search')
    rt('crm.company.show_search', '/crm/company/show_search')
    rt('crm.company.list', '/crm/company/list')
    rt('crm.company.enterprise.list', '/crm/company/enterprise/list')
    rt('crm.company.enterprise.new', '/crm/company/enterprise/new')
    rt('crm.company.enterprise.edit', '/crm/company/enterprise/edit/{enterprise_id}')
    rt('crm.company.enterprise.save', '/crm/company/enterprise/save')
    rt('crm.company.enterprise.provision', '/crm/company/provision')
    rt('crm.company.enterprise.quickstart', '/crm/company/quickstart')
    rt('crm.company.enterprise.clearcache', '/crm/company/enterprise/clearcache')

    rt('crm.product.new', '/crm/product/new') # ='crm/product', action='new')
    rt('crm.product.edit', '/crm/product/edit/{product_id}') # ='crm/product', action='edit')
    rt('crm.product.show_barcode', '/crm/product/show_barcode/{product_id}') # ='crm/product', action='show_barcode')
    rt('crm.product.save', '/crm/product/save') # ='crm/product', action='save')
    rt('crm.product.search', '/crm/product/search') # ='crm/product', action='search')
    rt('crm.product.list', '/crm/product/list') # ='crm/product', action='list')
    rt('crm.product.json', '/crm/product/json/{product_id}/{campaign_id}') # ='crm/product', action='json')
    rt('crm.product.barcodes', '/crm/product/barcodes') # ='crm/product', action='barcodes')
    rt('crm.product.ac.name', '/crm/product/autocomplete_by_name') # ='crm/product', action='autocomplete_by_name')
    rt('crm.product.show_orders', '/crm/product/show_orders/{product_id}') # ='crm/product', action='show_orders')
    rt('crm.product.show_sales', '/crm/product/show_sales/{product_id}') # ='crm/product', action='show_sales')
    rt('crm.product.show_purchases', '/crm/product/show_purchases/{product_id}') # ='crm/product', action='show_purchases')
    rt('crm.product.show_history', '/crm/product/show_history/{product_id}') # ='crm/product', action='show_history')
    rt('crm.product.show_returns', '/crm/product/show_returns/{product_id}') # ='crm/product', action='show_returns')
    rt('crm.product.show_status_dialog', '/crm/product/show_status_dialog/{product_id}/{status_id}') # ='crm/product', action='show_status_dialog')
    rt('crm.product.save_status', '/crm/product/save_status') # ='crm/product', action='save_status')
    rt('crm.product.show_inventory', '/crm/product/show_inventory') # ='crm/product', action='show_inventory')
    rt('crm.product.save_inventory', '/crm/product/save_inventory') # ='crm/product', action='save_inventory')
    rt('crm.product.inventory_list', '/crm/product/inventory_list') # ='crm/product', action='inventory_list')

    rt('crm.product.category.new', '/crm/product/category/new') # ='crm/category', action='new')
    rt('crm.product.category.edit', '/crm/product/category/edit/{category_id}') # ='crm/category', action='edit')
    rt('crm.product.category.save', '/crm/product/category/save') # ='crm/category', action='save')
    rt('crm.product.category.list', '/crm/product/category/list') # ='crm/category', action='list')

    rt('crm.communication.new', '/crm/communication/new') #, controller='crm/communication', action='new')
    rt('crm.communication.edit', '/crm/communication/edit/{comm_id}') #, controller='crm/communication', action='edit')
    rt('crm.communication.save', '/crm/communication/save') #, controller='crm/communication', action='save')
    rt('crm.communication.list', '/crm/communication/list') #, controller='crm/communication', action='list')
    rt('crm.communication.send_comm_dialog', '/crm/communication/send_comm_dialog') #, controller='crm/communication', action='send_comm_dialog')
    rt('crm.communication.send_customer_comm', '/crm/communication/send_customer_comm/{customer_id}/{comm_id}') #, controller='crm/communication', action='send_customer_comm')
    rt('crm.communication.view_comm_dialog', '/crm/communication/view_comm_dialog/{customer_id}/{comm_id}') #, controller='crm/communication', action='view_comm_dialog')

    rt('crm.users.new', '/crm/users/new') #controller='crm/users', action='new')
    rt('crm.users.edit', '/crm/users/edit/{username}') #controller='crm/users', action='edit')
    rt('crm.users.edit_current', '/crm/users/edit_current') #controller='crm/users', action='edit_current')
    rt('crm.users.save', '/crm/users/save') #controller='crm/users', action='save')
    rt('crm.users.save_password', '/crm/users/save_password') #controller='crm/users', action='save_password')
    rt('crm.users.search', '/crm/users/search') #controller='crm/users', action='search')
    rt('crm.users.list', '/crm/users/list') #controller='crm/users', action='list')

    rt('crm.event.new', '/crm/event/new') #, controller='crm/event', action='new')
    rt('crm.event.edit', '/crm/event/edit/{event_id}') #, controller='crm/event', action='edit')
    rt('crm.event.save', '/crm/event/save') #, controller='crm/event', action='save')
    rt('crm.event.search', '/crm/event/search') #, controller='crm/event', action='search')
    rt('crm.event.list', '/crm/event/list') #, controller='crm/event', action='list')

    rt('crm.report.new', '/crm/report/new') #, controller='crm/report', action='new')
    rt('crm.report.edit', '/crm/report/edit/{report_id}') #, controller='crm/report', action='edit')
    rt('crm.report.show', '/crm/report/show/{report_id}') #, controller='crm/report', action='show')
    rt('crm.report.list', '/crm/report/list') #, controller='crm/report', action='list')
    rt('crm.report.save', '/crm/report/save') #, controller='crm/report', action='save')
    rt('crm.report.results', '/crm/report/results/{report_id}') #, controller='crm/report', action='results')
    rt('crm.report.export', '/crm/report/results_export/{report_id}') #, controller='crm/report', action='results_export')

    
    rt('crm.purchase.vendor.new', '/crm/purchase/vendor/new')  #, controller='crm/purchase', action='new_vendor')
    rt('crm.purchase.vendor.edit', '/crm/purchase/vendor/edit/{vendor_id}')  #controller='crm/purchase', action='edit_vendor')
    rt('crm.purchase.vendor.list', '/crm/purchase/vendor/list')  #, controller='crm/purchase', action='list_vendors')
    rt('crm.purchase.vendor.save', '/crm/purchase/vendor/save')  #, controller='crm/purchase', action='save_vendor')
    rt('crm.purchase.new', '/crm/purchase/new')  #, controller='crm/purchase', action='new')
    rt('crm.purchase.edit', '/crm/purchase/edit/{purchase_order_id}')  #, controller='crm/purchase', action='edit')
    rt('crm.purchase.list', '/crm/purchase/list')  #, controller='crm/purchase', action='list')
    rt('crm.purchase.save', '/crm/purchase/save')  #, controller='crm/purchase', action='save')
    rt('crm.purchase.search', '/crm/purchase/search')
    rt('crm.purchase.show_search', '/crm/purchase/show_search')
    rt('crm.purchase.order_item_json', '/crm/purchase/order_item_json/{purchase_order_id}/{order_item_id}')  #, controller='crm/purchase', action='order_item_json')
    rt('crm.purchase.save_purchase_order_item', '/crm/purchase/save_purchase_order_item/{purchase_order_id}')  #, controller='crm/purchase', action='save_purchase_order_item')
    rt('crm.purchase.delete_purchase_order_item', '/crm/purchase/delete_purchase_order_item/{purchase_order_id}/{order_item_id}')  #, controller='crm/purchase', action='delete_purchase_order_item')
    rt('crm.purchase.show_history', '/crm/purchase/show_history/{purchase_order_id}')  #, controller='crm/purchase', action='show_history')
    rt('crm.purchase.status_dialog', '/crm/purchase/status_dialog/{purchase_order_id}')  #, controller='crm/purchase', action='status_dialog')
    rt('crm.purchase.show_status_dialog', '/crm/purchase/show_status_dialog/{purchase_order_id}/{status_id}')  #, controller='crm/purchase', action='show_status_dialog')
    rt('crm.purchase.save_status', '/crm/purchase/save_status/{purchase_order_id}')  #, controller='crm/purchase', action='save_status')
    rt('crm.purchase.complete', '/crm/purchase/complete/{purchase_order_id}')  #, controller='crm/purchase', action='complete')
    rt('crm.purchase.complete_item', '/crm/purchase/complete_item/{purchase_order_id}/{order_item_id}')  #, controller='crm/purchase', action='complete_item')

    rt('crm.customer.new', '/crm/customer/new') # controller='crm/customer', action='new')
    rt('crm.customer.edit', '/crm/customer/edit/{customer_id}') # controller='crm/customer', action='edit')
    rt('crm.customer.editbye', '/crm/customer/edit_by_email/{customer_id}/{enterprise_id}') # controller='crm/customer', action='edit_by_email')
    rt('crm.customer.save', '/crm/customer/save') # controller='crm/customer', action='save')
    rt('crm.customer.delete', '/crm/customer/delete/{customer_id}') # controller='crm/customer', action='delete')
    rt('crm.customer.search', '/crm/customer/search') # controller='crm/customer', action='search')
    rt('crm.customer.edit_billing', '/crm/customer/edit_billing/{customer_id}') # controller='crm/customer', action='edit_billing')
    rt('crm.customer.edit_billing_dialog', '/crm/customer/edit_billing_dialog/{customer_id}') # controller='crm/customer', action='edit_billing_dialog')
    rt('crm.customer.apply_payment_dialog', '/crm/customer/apply_payment_dialog/{customer_id}/{order_id}') # controller='crm/customer', action='apply_payment_dialog')
    rt('crm.customer.apply_payment', '/crm/customer/apply_payment/{customer_id}/{order_id}') # controller='crm/customer', action='apply_payment')
    rt('crm.customer.return_item_dialog', '/crm/customer/return_item_dialog/{customer_id}/{order_id}/{order_item_id}') # controller='crm/customer', action='return_item_dialog')
    rt('crm.customer.return_item', '/crm/customer/return_item/{customer_id}/{order_id}/{order_item_id}') # controller='crm/customer', action='return_item')
    rt('crm.customer.add_order', '/crm/customer/add_order/{customer_id}') # controller='crm/customer', action='add_order')
    rt('crm.customer.add_order_and_apply', '/crm/customer/add_order_and_apply/{customer_id}/{pmt_method}') # controller='crm/customer', action='add_order_and_apply')
    rt('crm.customer.add_order_dialog', '/crm/customer/add_order_dialog/{customer_id}') # controller='crm/customer', action='add_order_dialog')
    rt('crm.customer.add_order_item', '/crm/customer/add_order/{customer_id}/{order_id}') # controller='crm/customer', action='add_order_item')
    rt('crm.customer.add_order_item_dialog', '/crm/customer/add_order_item_dialog/{customer_id}/{order_id}') # controller='crm/customer', action='add_order_item_dialog')
    rt('crm.customer.cancel_order', '/crm/customer/cancel_order/{customer_id}') # controller='crm/customer', action='cancel_order')
    rt('crm.customer.edit_order', '/crm/customer/edit_order/{customer_id}/{order_id}') # controller='crm/customer', action='edit_order')
    rt('crm.customer.edit_order_dialog', '/crm/customer/edit_order_dialog/{customer_id}/{order_id}') # controller='crm/customer', action='edit_order_dialog')
    rt('crm.customer.show_orders', '/crm/customer/show_orders/{customer_id}') # controller='crm/customer', action='show_orders')
    rt('crm.customer.show_history', '/crm/customer/show_history/{customer_id}') # controller='crm/customer', action='show_history')
    rt('crm.customer.show_attributes', '/crm/customer/show_attributes/{customer_id}') # controller='crm/customer', action='show_attributes')
    rt('crm.customer.show_appointments', '/crm/customer/show_appointments/{customer_id}') # controller='crm/customer', action='show_appointments')
    rt('crm.customer.show_billings', '/crm/customer/show_billings/{customer_id}') # controller='crm/customer', action='show_billings')
    rt('crm.customer.autocomplete.name', '/crm/customer/autocomplete') # controller='crm/customer', action='autocomplete')
    rt('crm.customer.show_summary', '/crm/customer/show_summary/{customer_id}') # controller='crm/customer', action='show_summary')
    rt('crm.customer.self_change_password', '/crm/customer/self_change_password') # controller='crm/customer', action='self_change_password')
    rt('crm.customer.self_save', '/crm/customer/self_save') # controller='crm/customer', action='self_save')
    rt('crm.customer.self_cancel_order', '/crm/customer/self_cancel_order') # controller='crm/customer', action='self_cancel_order')
    rt('crm.customer.self_save_billing', '/crm/customer/self_save_billing') # controller='crm/customer', action='self_save_billing')
    rt('crm.customer.signup', '/crm/customer/signup') # controller='crm/customer', action='signup')
    rt('crm.customer.signup_and_purchase', '/crm/customer/signup_and_purchase') # controller='crm/customer', action='signup_and_purchase')
    rt('crm.customer.signup_free', '/crm/customer/signup_free') # controller='crm/customer', action='signup_free')
    rt('crm.customer.cancel_billing', '/crm/customer/cancel_billing/{customer_id}/{journal_id}') # controller='crm/customer', action='cancel_billing')
    rt('crm.customer.check_duplicate_email', '/crm/customer/check_duplicate_email/{email}') # controller='crm/customer', action='check_duplicate_email')
    rt('crm.customer.save_and_purchase', '/crm/customer/save_and_purchase') # controller='crm/customer', action='save_and_purchase')
    rt('crm.customer.status_dialog', '/crm/customer/status_dialog/{customer_id}') # controller='crm/customer', action='status_dialog')
    rt('crm.customer.show_status_dialog', '/crm/customer/show_status_dialog/{customer_id}/{status_id}') # controller='crm/customer', action='show_status_dialog')
    rt('crm.customer.save_status', '/crm/customer/save_status/{customer_id}') # controller='crm/customer', action='save_status')
    rt('crm.customer.show_billing_dialog', '/crm/customer/show_billing_dialog/{customer_id}/{journal_id}') # controller='crm/customer', action='show_billing_dialog')
    rt('crm.customer.get_balance', '/crm/customer/get_balance/{customer_id}') # controller='crm/customer', action='get_balance')

    rt('crm.dashboard', '/crm/dashboard')

    """

    rt('crm.cust.login.post', '/crm/customer_login', controller='crm/login', action='customer_login')
    rt('crm.cust.login.forgot', '/crm/customer_forgot_password', controller='crm/login', action='customer_forgot_password')
    rt('crm.cust.login.login_to_link', '/crm/customer_login_to_link/{key}/{link}', controller='crm/login', action='customer_login_to_link')





    rt('crm.discount.dialog', '/crm/discount/dialog/{subdir}/{dlg}', controller='crm/discount', action='dialog')
    rt('crm.discount.new', '/crm/discount/new', controller='crm/discount', action='new')
    rt('crm.discount.edit', '/crm/discount/edit/{discount_id}', controller='crm/discount', action='edit')
    rt('crm.discount.save', '/crm/discount/save', controller='crm/discount', action='save')
    rt('crm.discount.list', '/crm/discount/list', controller='crm/discount', action='list')


    rt('api.product.list', '/api/product/list', controller='crm/product', action='list')

    rt('test.1', '/tsst/tsst_validate', controller='crm/tsst', action='tsst_validate')
    rt('test.1', '/tsst/tsst_validate_session', controller='crm/tsst', action='tsst_validate')
    rt('test.1', '/tsst/tsst_float', controller='crm/tsst', action='tsst_float')
    rt('test.1', '/tsst/tsst_int', controller='crm/tsst', action='tsst_int')
    rt('test.1', '/tsst/tsst_string', controller='crm/tsst', action='tsst_string')
    rt('test.1', '/tsst/tsst_number', controller='crm/tsst', action='tsst_number')
    rt('test.1', '/tsst/tsst_equals', controller='crm/tsst', action='tsst_equals')
    rt('test.1', '/tsst/tsst_redirto', controller='crm/tsst', action='tsst_redirto')
    rt('test.1', '/tsst/tsst_redirto_post', controller='crm/tsst', action='tsst_redirto_post')
    """
